
# train evaluation
CUDA_VISIBLE_DEVICES=4,5,6 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_antithetical \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_antithetical.json

CUDA_VISIBLE_DEVICES=0,2,3 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_long \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_long.json

CUDA_VISIBLE_DEVICES=4,5,6 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_train_sampling \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling.json

CUDA_VISIBLE_DEVICES=4,5,6 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_short \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_short.json


# validation evaluation

CUDA_VISIBLE_DEVICES=4,5,6 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_validation_sampling \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_validation_sampling.json

CUDA_VISIBLE_DEVICES=4,5,6 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_validation_sampling_short \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_validation_sampling_short.json

CUDA_VISIBLE_DEVICES=0,2,3 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_surrogate_banzhaf_eval_test_sampling_long \
python calculate_feature_attribution.py configs/vitbase_imagenette_surrogate_banzhaf_eval_test_sampling_long.json






CUDA_VISIBLE_DEVICES=4,5,6,7 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_global_500 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_global_500.json

CUDA_VISIBLE_DEVICES=0,1,2,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_global_100 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_global_100.json

CUDA_VISIBLE_DEVICES=2,5,6,7 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_global_10 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_global_10.json


CUDA_VISIBLE_DEVICES=0,1,2,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_sqrt_500 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_sqrt_500.json

CUDA_VISIBLE_DEVICES=1,2,3,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_sqrt_100 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_sqrt_100.json

CUDA_VISIBLE_DEVICES=0,1,2,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_sqrt_10 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_sqrt_10.json

CUDA_VISIBLE_DEVICES=1,2,3,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_perinstance_500 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_perinstance_500.json

CUDA_VISIBLE_DEVICES=1,2,3,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_perinstance_100 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_perinstance_100.json


CUDA_VISIBLE_DEVICES=1,2,3,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_perinstanceperclass_500 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_perinstanceperclass_500.json

CUDA_VISIBLE_DEVICES=1,2,3,5 \
WANDB_PROJECT=xai-amortization \
WANDB_NAME=vitbase_imagenette_banzhaf_regexplainer_upfront_perinstanceperclass_100 \
python train_regexplainer_normalize.py configs/vitbase_imagenette_banzhaf_regexplainer_upfront_perinstanceperclass_100.json

# tar zcvf logs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling.tar.gz logs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling/
# tar zcvf logs/vitbase_imagenette_surrogate_banzhaf_eval_validation_sampling.tar.gz logs/vitbase_imagenette_surrogate_banzhaf_eval_validation_sampling/
# tar zcvf logs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_long.tar.gz logs/vitbase_imagenette_surrogate_banzhaf_eval_train_sampling_long/
# tar zcvf logs/vitbase_imagenette_surrogate_model.tar.gz ./logs/vitbase_imagenette_surrogate_model


# 89/9456 1807
265 in progress